apiVersion: v1
kind: Service
metadata:
  name: jhipster-registry
  namespace: default
  labels:
    app: jhipster-registry
spec:
  selector:
    app: jhipster-registry
    type: LoadBalancer
  ports:
    - name: http
      port: 8761
