commonLabels:
  app.kubernetes.io/genereted-by: JHipster

resources:
  # Individual apps
  - artist-k8s/artist-deployment.yml
  - artist-k8s/artist-service.yml
  - artist-k8s/artist-mariadb.yml
  - artist-k8s/artist-prometheus-sm.yml
  - artist-k8s/artist-destination-rule.yml
  - artist-k8s/artist-virtual-service.yml
  - artwork-k8s/artwork-deployment.yml
  - artwork-k8s/artwork-service.yml
  - artwork-k8s/artwork-mariadb.yml
  - artwork-k8s/artwork-prometheus-sm.yml
  - artwork-k8s/artwork-destination-rule.yml
  - artwork-k8s/artwork-virtual-service.yml
  - gateway-k8s/gateway-deployment.yml
  - gateway-k8s/gateway-service.yml
  - gateway-k8s/gateway-mariadb.yml
  - gateway-k8s/gateway-gateway.yml
  - gateway-k8s/gateway-prometheus-sm.yml
  - gateway-k8s/gateway-destination-rule.yml
  - gateway-k8s/gateway-virtual-service.yml
  # messagebroker
  - messagebroker-k8s/kafka.yml
  # monitoring prometheus
  - monitoring-k8s/jhipster-prometheus-cr.yml
  - monitoring-k8s/jhipster-prometheus-crd.yml
  - monitoring-k8s/jhipster-grafana.yml
  - monitoring-k8s/jhipster-grafana-dashboard.yml
  - monitoring-k8s/jhipster-grafana-gateway.yml
  # service discovery eureka/consul
  - registry-k8s/jhipster-registry.yml
  - registry-k8s/application-configmap.yml
  # istio
  - istio-k8s/grafana-gateway.yml
  - istio-k8s/zipkin-gateway.yml
  - istio-k8s/kiali-gateway.yml

patchesJson6902:
  - target:
      version: v1
      kind: Namespace
      name: default
    path: patch-k8s/istio-label.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: Gateway
      name: grafana-observability-gateway
      namespace: default
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      name: grafana-gw-virtualservice
      kind: VirtualService
      namespace: default
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: Gateway
      name: kiali-observability-gateway
      namespace: default
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      name: kiali-gw-virtualservice
      kind: VirtualService
      namespace: default
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: Gateway
      name: zipkin-observability-gateway
      namespace: default
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      name: zipkin-gw-virtualservice
      kind: VirtualService
      namespace: default
    path: patch-k8s/istio-namespace.yml
