apiVersion: v1
kind: Service
metadata:
  name: artwork
  namespace: default
  labels:
    app: artwork
spec:
  selector:
    app: artwork
  type: LoadBalancer
  ports:
    - name: http
      port: 8002
